routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MedecinController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//auth route for both 
Route::group(['middleware' => ['auth']], function() { 
    Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard');
});

// for users
Route::group(['middleware' => ['auth', 'role:user']], function() { 
    Route::get('/dashboard/monprofil', 'App\Http\Controllers\DashboardController@monprofil')->name('dashboard.monprofil');
    Route::resource('consultation', DashboardController::class);

});

// for admin
Route::group(['middleware' => ['auth', 'role:admin']], function() { 
    Route::resource('user', UserController::class);
});

//for doctor
Route::group(['middleware' => ['auth', 'role:medecin']], function() { 
    Route::resource('doctor', MedecinController::class);

});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/create-user.blade.php
<x-app-layout>

<x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create an users') }}
        </h2>
</x-slot>

    <x-admin-auth-card>
        <x-slot name="logo">
            <a href="/">
                <x-application-logo class="w-20 h-20 fill-current text-gray-500" />
            </a>
        </x-slot>

        <!-- Validation Errors -->
        <x-auth-validation-errors class="mb-4" :errors="$errors" />

        <form method="POST" action="{{ route('user.store') }}">
            @csrf

            <!-- Name -->
            <div>
                <x-label for="name" :value="__('Nom')" />

                <x-input id="name" class="block mt-1 w-full" type="text" name="name" :value="old('name')" required autofocus />
            </div>

            <!-- Email Address -->
            <div class="mt-4">
                <x-label for="email" :value="__('Email')" />

                <x-input id="email" class="block mt-1 w-full" type="email" name="email" :value="old('email')" required />
            </div>

            <!-- Password -->
            <div class="mt-4">
                <x-label for="password" :value="__('mot de passe')" />

                <x-input id="password" class="block mt-1 w-full"
                                type="password"
                                name="password"
                                required autocomplete="new-password" />
            </div>

            <!-- Confirm Password -->
            <div class="mt-4">
                <x-label for="password_confirmation" :value="__('Confirmer le mot de passe')" />

                <x-input id="password_confirmation" class="block mt-1 w-full"
                                type="password"
                                name="password_confirmation" required />
            </div>

            
            <!-- Select Option Rol type -->
            <div class="mt-4">
                    <x-label for="role_id" value="{{ __('Creer un') }}" />
                    <select name="role_id" class="block mt-1 w-full border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-md shadow-sm">
                        <option value="user">Utilisateur</option>
                        <option value="medecin">Medecin</option>
                        <option value="medecin">Admin</option>
                    </select>
            </div>

            <div class="flex items-center justify-end mt-4">
                <x-button class="ml-4">
                    {{ __('Créer') }}
                </x-button>
            </div>
        </form>
        
    </x-admin-auth-card>


</x-app-layout>

resources/views/admin/edit-user.blade.php
<x-app-layout>

  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      {{ __('Create an users') }}
    </h2>
  </x-slot>

  <x-admin-auth-card>
    <x-slot name="logo">
      <a href="/">
        <x-application-logo class="w-20 h-20 fill-current text-gray-500" />
      </a>
    </x-slot>

    <!-- Validation Errors -->
    <x-auth-validation-errors class="mb-4" :errors="$errors" />

    <form method="POST" action="{{ route('user.update', $user->id) }}">
      @csrf
      @method('PUT')
      <!-- Name -->
      <div>
        <x-label for="name" :value="__('Nom')" />

        <x-input id="name" class="block mt-1 w-full" type="text" name="name" :value="$user->name" required autofocus />
      </div>

      <!-- Email Address -->
      <div class="mt-4">
        <x-label for="email" :value="__('Email')" />

        <x-input id="email" class="block mt-1 w-full" type="email" name="email" :value="$user->email" required />
      </div>

      <!-- Select Option Rol type -->
      <div class="mt-4">
      @foreach ($user->roles as $role)
        <x-label for="role_id" value="Role actuel : {{ $role->display_name }}" />
        @endforeach
        <select name="role_id" class="block mt-1 w-full border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-md shadow-sm">
          <option value="user">Utilisateur</option>
          <option value="medecin">Medecin</option>
          <option value="medecin">Admin</option>
        </select>
      </div>

      <div class="flex items-center justify-end mt-4">
        <x-button class="ml-4">
          {{ __('Modifier') }}
        </x-button>
      </div>
    </form>

  </x-admin-auth-card>


</x-app-layout>

resources/views/admin/lists-user.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      {{ __('Dashboard admin') }}
    </h2>
  </x-slot>
  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
      <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <table class="min-w-max w-full table-auto">
          <thead>
            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
              <th class="py-3 px-6 text-left">id</th>
              <th class="py-3 px-6 text-left">name</th>
              <th class="py-3 px-6 text-center">email</th>
              <th class="py-3 px-6 text-center">date création</th>
              <th class="py-3 px-6 text-center">role</th>
              <th class="py-3 px-6 text-center">Actions</th>
            </tr>
          </thead>
          @foreach ($users as $user)
          <tbody class="text-gray-600 text-sm font-light">
            <tr class="border-b border-gray-200 hover:bg-gray-100">

              <td class="py-3 px-6 text-left">
                <div class="flex items-center">
                  <span class="font-medium">{{$user->id}}</span>
                </div>
              </td>
              <td class="py-3 px-6 text-left">
                <div class="flex items-center">
                  <span class="font-medium">{{$user->name}}</span>
                </div>
              </td>
              <td class="py-3 px-6 text-left">
                <div class="flex items-center">
                  <span class="font-medium">{{$user->email}}</span>
                </div>
              </td>
              <td class="py-3 px-6 text-left">
                <div class="flex items-center">
                  <span class="font-medium">{{$user->created_at}}</span>
                </div>
              </td>
              <td class="py-3 px-6 text-center">
                @foreach ($user->roles as $role)
                <span class="bg-purple-200 text-purple-600 py-1 px-3 rounded-full text-xs">{{$role->name}}</span>
                @endforeach
              </td>

              <td class="py-3 px-6 text-center">
                <div class="flex item-center justify-center space-x-4">
                  <a href="{{ route('user.edit', $user->id)}}"
                    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
                    Edit
                  </a>
                  <form action="{{ route('user.destroy', $user->id) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-full"" type="submit">Supprimer
                    </button>
                  </form>
                </div>
              </td>
            </tr>
          </tbody>
          @endforeach
        </table>

      </div>
    </div>
  </div>
  </div>
</x-app-layout>